title: Yumou Liu's Homepage
page-top-title: Yumou Liu
top-section-bg-text: Computer Science
home-subtitle: Yumou Liu&ensp;|&ensp;刘禹谋
copyright-text: '&copy; Yumou Liu 2024-2025. All Rights Reserved.'
